"use client";

import type { Metadata } from "next";
import localFont from "next/font/local";
import { usePathname } from "next/navigation"; // Import usePathname
import "./globals.css";
import Navbar from "./(components)/Navbar";
import Sidebar from "./(components)/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // Get the current pathname
  const isDashboardPage = pathname === "/"; // Check if the current route is the home page

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar /> */}
        {isDashboardPage && <Navbar />}
        {isDashboardPage && <Sidebar />}{" "}
        {/* Conditionally render the Sidebar */}
        {children}
      </body>
    </html>
  );
}
